version: "3.0"

services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - jm_network
    ports:
      - 9200:9200

  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - jm_network
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  python_container:
    container_name: python_container
    image: davidros/jm_project
    networks:
      - jm_network
    ports:
      - 8888:8888
    volumes:
      - ${PWD}:/home/jovyan/ 
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

networks:
  jm_network:
    driver: bridge